name: Build

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Restore Dependencies
        run: npm ci

      - name: Lint and Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Verify No Unstaged Changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            echo git status
            git status
            echo git diff
            git diff
            echo "::error::Unstaged changes detected."
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Run
        uses: ./
